# Supabase Project Configuration

[project]
# Project ID will be set when linked to a Supabase project
id = ""

[api]
enabled = true
port = 54321
max_rows = 1000

[db]
port = 54322
major_version = 15

[db.pooler]
enabled = false
port = 54329

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[storage.image_transformation]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://castchat.jp", "https://staging.castchat.jp"]

[auth.external.google]
enabled = true
client_id = "244502393612-t7fvuqf9rg2kssse5b1i5qvaqha605fs.apps.googleusercontent.com"
secret = "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"
redirect_uri = "http://localhost:54321/auth/v1/callback"

[auth.email]
enable_signup = true
enable_confirmations = true
max_frequency = "1h"
otp_expiry = 3600

[auth.sms]
enable_signup = false
enable_confirmations = false

[analytics]
enabled = false

[mailer]
# Email settings will be configured in Supabase dashboard

[server]
# Regional configuration
region = "ap-northeast-1"